<div id="featuredPromo">
    <img src="/pulsar-temp/images/promos/sample_banner.png" alt="Promo" />
</div>

<div class="hr"><hr/></div>

<div id="featuredProductsWrapper" class="clearfix">
    <ul id="featuredProductList">
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/NC656XX.jpg" alt="Utensils" />
                <span class="productName">Kitchen and Dining Utensils for Eating Things With</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$2499.99</div>
                <a href="#" class="right viewOptions">View Details</a>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/renavite.jpg" alt="Utensils" />
                <span class="productName">Bottle of Peels</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$4.99</div>
                <div class="right button">
                    <span class="addToCart">Add to Cart</span>
                </div>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/NC656XX.jpg" alt="Utensils" />
                <span class="productName">Kitchen and Dining Utensils for Eating Things With</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$2499.99</div>
                <a href="#" class="right viewOptions">View Details</a>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/renavite.jpg" alt="Utensils" />
                <span class="productName">Bottle of Peels</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$4.99</div>
                <div class="right button">
                    <span class="addToCart">Add to Cart</span>
                </div>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/NC656XX.jpg" alt="Utensils" />
                <span class="productName">Kitchen and Dining Utensils for Eating Things With</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$2499.99</div>
                <a href="#" class="right viewOptions">View Details</a>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/renavite.jpg" alt="Utensils" />
                <span class="productName">Bottle of Peels</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$4.99</div>
                <div class="right button">
                    <span class="addToCart">Add to Cart</span>
                </div>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/NC656XX.jpg" alt="Utensils" />
                <span class="productName">Kitchen and Dining Utensils for Eating Things With</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$2499.99</div>
                <a href="#" class="right viewOptions">View Details</a>
            </div>
        </li>
        <li class="featuredProduct">
            <a href="#" class="productLink">
                <img src="http://www.southwestmedical.com/fs/100/images/products/images/renavite.jpg" alt="Utensils" />
                <span class="productName">Bottle of Peels</span>
            </a>
            <div class="priceBox clearfix">
                <div class="left price">$4.99</div>
                <div class="right button">
                    <span class="addToCart">Add to Cart</span>
                </div>
            </div>
        </li>
    </ul>
</div>